spring.application.name=backend

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.datasource.url=jdbc:mysql://localhost:3306/incident_analysis
spring.datasource.username=incident_user
spring.datasource.password=Incident123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

